// AUTHORED-BY Claude Opus 4.8
/**
 * Emit the generated artifacts (design §7): model.json (the verified projection),
 * model.js (a FIXED-TEMPLATE shim that inlines the manifest and calls
 * `@jeswr/model-runtime` — its bytes vary only in the JSON), model.d.ts (types
 * only, zero runtime code), and shapes.ttl (the byte-reproducible stable waist).
 * A generated artifact contains NO executable logic beyond the fixed shim.
 *
 * COMPOSITE PER-NODE VIEWS: when the manifest carries composite entities, model.js
 * additionally inlines the derived node-views manifest + index (see `nodeviews.ts`)
 * and exposes `nodes` — one typed per-node Wrapper handle per composite sub-node.
 * The per-node section is PART OF THE FIXED TEMPLATE (identical bytes for every
 * generated model; only the two inlined JSON blobs vary), and all behaviour still
 * runs through the audited runtime's `defineModel` — the template merely zips the
 * inlined index DATA with the interpreted view model. (Follow-up consolidation:
 * once `@jeswr/model-runtime` exposes per-node wrappers natively on a composite
 * entity, this template section collapses to a re-export.)
 */

import {
  type AnyManifestEntity,
  isCompositeEntity,
  literalMapper,
  type ManifestField,
  type ModelManifest,
} from "@jeswr/model-runtime";
import type { NodeViews } from "./nodeviews.js";
import { serializeCanonicalTurtle } from "./rdf.js";
import type { NormalizedShapes } from "./shapes.js";

const GENERATED_HEADER =
  "// AUTHORED-BY Claude Opus 4.8\n" +
  "// GENERATED by @jeswr/federation-codegen — DO NOT EDIT.\n" +
  "// All behaviour lives in the audited @jeswr/model-runtime; this file is data + a fixed shim.\n";

/** model.json — the compiled manifest, pretty-printed + trailing newline. */
export function emitModelJson(manifest: ModelManifest): string {
  return `${JSON.stringify(manifest, null, 2)}\n`;
}

// The fixed per-node-views template section (bytes vary only in the two JSON blobs
// interpolated above it). Pure data-zipping: the ONLY behaviour invoked is the
// audited runtime's `defineModel` on the derived (generation-time, fidelity-rooted)
// view manifest; the handles then pair each index entry with its view Wrapper.
const NODE_VIEWS_TEMPLATE =
  `const nodeViews = defineModel(nodeViewsManifest);\n` +
  `export const nodes = Object.freeze(\n` +
  `  Object.fromEntries(\n` +
  `    Object.entries(nodeViewIndex).map(([compositeName, nodesOf]) => [\n` +
  `      compositeName,\n` +
  `      Object.freeze(\n` +
  `        Object.fromEntries(\n` +
  `          Object.entries(nodesOf).map(([nodeName, view]) => [\n` +
  `            nodeName,\n` +
  `            Object.freeze({\n` +
  `              name: nodeName,\n` +
  `              typeIri: view.typeIri,\n` +
  `              fragment: view.fragment,\n` +
  `              Wrapper: nodeViews.entities[view.entity].Wrapper,\n` +
  `              subject: (resourceUrl) => \`\${resourceUrl}#\${view.fragment}\`,\n` +
  `            }),\n` +
  `          ]),\n` +
  `        ),\n` +
  `      ),\n` +
  `    ]),\n` +
  `  ),\n` +
  `);\n`;

/** model.js — the fixed-template shim (bytes vary only in the inlined manifests). */
export function emitModelJs(manifest: ModelManifest, nodeViews?: NodeViews): string {
  const json = JSON.stringify(manifest, null, 2);
  const base =
    `${GENERATED_HEADER}` +
    `import { defineModel } from "@jeswr/model-runtime";\n\n` +
    `const manifest = ${json};\n\n` +
    `const model = defineModel(manifest);\n` +
    `export default model;\n` +
    `export const { entities } = model;\n`;
  if (nodeViews === undefined) {
    // No composite entity — the export surface stays uniform (an empty handle map).
    return `${base}\n// No composite entities — no per-node views.\nexport const nodes = Object.freeze({});\n`;
  }
  const viewsJson = JSON.stringify(nodeViews.manifest, null, 2);
  const indexJson = JSON.stringify(nodeViews.index, null, 2);
  return (
    `${base}\n` +
    `// COMPOSITE PER-NODE VIEWS — one typed Wrapper per composite sub-node, interpreted\n` +
    `// through the SAME audited defineModel path. The view manifest + index below are\n` +
    `// DERIVED at generation time from the manifest above (a nested link is projected as\n` +
    `// a plain IRI field); only the view Wrappers are surfaced — a handle's subject() is\n` +
    `// the fragment-correct node IRI. Fixed template; only the JSON varies.\n` +
    `const nodeViewsManifest = ${viewsJson};\n\n` +
    `const nodeViewIndex = ${indexJson};\n\n` +
    NODE_VIEWS_TEMPLATE
  );
}

function baseTsType(field: ManifestField): string {
  // A closed `sh:in` value set narrows the field to a literal union.
  if (field.in !== undefined && field.in.length > 0) {
    return field.in.map((v) => (typeof v === "string" ? JSON.stringify(v) : String(v))).join(" | ");
  }
  if (field.kind === "iri") return "string";
  if (field.datatype === undefined) return "string";
  // Single-source the datatype → TS-type decision through the audited runtime's
  // `literalMapper` (the SAME resolution the runtime reads/writes against, and that
  // `shapes.ts` coerces `sh:in` scalars by), so the emitted type can never disagree
  // with the runtime's JS surface type — e.g. the unsigned XSD integer subtypes.
  switch (literalMapper(field.datatype).jsType) {
    case "number":
      return "number";
    case "boolean":
      return "boolean";
    case "date":
      return "Date";
    default:
      return "string";
  }
}

// Requiredness in `*Data` must track the RUNTIME ADMISSION CONTRACT, not shape
// cardinality alone. Under G1 severity-aware requiredness, an advisory
// (`sh:Warning`/`sh:Info`-graded) `sh:minCount ≥ 1` field is ADMITTED at runtime when
// ABSENT — it compiles to NO `requiredFailClosed` guard — so typing it required in
// `*Data` would make the static type reject objects the runtime accepts. A field is
// required iff it carries the fail-closed required guard (Violation-graded / ungraded
// `minCount ≥ 1`, or a config-declared `requiredFailClosed: true`).
function isRequired(field: ManifestField): boolean {
  return field.guards?.requiredFailClosed === true;
}

// Property names are JSON.stringify-quoted so ANY field name is a valid .d.ts
// property key (defence in depth — the runtime already validates names against
// an identifier charset + reserved-name denylist, but quoting makes the emitted
// declaration robust regardless).
function propKey(name: string): string {
  return JSON.stringify(name);
}

function dataFieldLine(field: ManifestField): string {
  const base = baseTsType(field);
  if (field.collection === "set") {
    return `  ${propKey(field.name)}?: ${base}[];`;
  }
  const opt = isRequired(field) ? "" : "?";
  return `  ${propKey(field.name)}${opt}: ${base};`;
}

function wrapperFieldLine(field: ManifestField): string {
  const base = baseTsType(field);
  if (field.collection === "set") {
    return `  readonly ${propKey(field.name)}: Set<${base}>;`;
  }
  // A single accessor's setter accepts `undefined` (to clear the triple), so the
  // property is optional even for a default-bearing field (the getter still yields
  // a value at runtime — the default — but the type must permit the clearing write).
  return `  ${propKey(field.name)}?: ${base};`;
}

// A composite projects a FLAT object across its nodes' flat (non-nested) fields; its
// `Wrapper` is the ROOT node's wrapper (matching the runtime's rootRt.Wrapper), so the
// wrapper interface types only the root node's flat fields.
function compositeFieldLines(entity: AnyManifestEntity): {
  dataLines: string;
  wrapperLines: string;
} {
  if (!isCompositeEntity(entity)) {
    return {
      dataLines: entity.fields.map(dataFieldLine).join("\n"),
      wrapperLines: entity.fields.map(wrapperFieldLine).join("\n"),
    };
  }
  const flat = (fields: ManifestField[]) => fields.filter((f) => f.kind !== "nested");
  const dataFields = entity.nodes.flatMap((n) => flat(n.fields));
  const rootNode = entity.nodes.find((n) => n.name === entity.root);
  const rootFields = flat(rootNode?.fields ?? []);
  return {
    dataLines: dataFields.map(dataFieldLine).join("\n"),
    wrapperLines: rootFields.map(wrapperFieldLine).join("\n"),
  };
}

function entityDts(entity: AnyManifestEntity): string {
  const name = entity.name;
  const { dataLines, wrapperLines } = compositeFieldLines(entity);
  return (
    `export interface ${name}Data {\n${dataLines}\n}\n\n` +
    `export interface ${name}Wrapper extends EntityWrapper {\n${wrapperLines}\n}\n\n` +
    `export interface ${name}Entity {\n` +
    `  readonly name: "${name}";\n` +
    `  readonly typeIri: string;\n` +
    `  readonly Wrapper: new (\n` +
    `    term: string | Term,\n` +
    `    dataset: DatasetCore,\n` +
    `    factory: DataFactory,\n` +
    `  ) => ${name}Wrapper;\n` +
    `  subject(resourceUrl: string): string;\n` +
    `  build(resourceUrl: string, data: ${name}Data): Store;\n` +
    `  parse(resourceUrl: string, dataset: DatasetCore): ${name}Data | undefined;\n` +
    `  serialize(resourceUrl: string, data: ${name}Data): Promise<string>;\n` +
    `  storeToTurtle(store: Store): Promise<string>;\n` +
    `  parseDocument(\n` +
    `    resourceUrl: string,\n` +
    `    body: string,\n` +
    `    contentType?: string | null,\n` +
    `  ): Promise<${name}Data | undefined>;\n` +
    `}\n`
  );
}

// The generic handle interface emitted alongside per-node views (fixed text).
const NODE_HANDLE_DTS =
  `/** A typed view handle onto ONE sub-node of a composite entity. */\n` +
  `export interface CompositeNodeHandle<W extends EntityWrapper> {\n` +
  `  readonly name: string;\n` +
  `  readonly typeIri: string;\n` +
  `  readonly fragment: string;\n` +
  `  readonly Wrapper: new (\n` +
  `    term: string | Term,\n` +
  `    dataset: DatasetCore,\n` +
  `    factory: DataFactory,\n` +
  `  ) => W;\n` +
  `  subject(resourceUrl: string): string;\n` +
  `}\n`;

// Per-node view typing: one `<ViewName>Wrapper` interface per composite sub-node
// (typed over the view's flat fields — a nested link surfaces as an IRI accessor),
// plus the `nodes` handle-map declaration mirroring the emitted model.js export.
function nodeViewsDts(nodeViews: NodeViews | undefined): string {
  if (nodeViews === undefined) {
    return `export declare const nodes: Readonly<Record<string, never>>;\n`;
  }
  const viewByName = new Map(nodeViews.manifest.entities.map((e) => [e.name, e]));
  const wrapperBlocks: string[] = [];
  const compositeLines: string[] = [];
  for (const [compositeName, nodesOf] of Object.entries(nodeViews.index)) {
    const nodeLines: string[] = [];
    for (const [nodeName, ref] of Object.entries(nodesOf)) {
      const view = viewByName.get(ref.entity);
      if (view === undefined || isCompositeEntity(view)) {
        throw new Error(`node view index references unknown view entity "${ref.entity}"`);
      }
      wrapperBlocks.push(
        `export interface ${ref.entity}Wrapper extends EntityWrapper {\n` +
          `${view.fields.map(wrapperFieldLine).join("\n")}\n}\n`,
      );
      nodeLines.push(
        `    readonly ${propKey(nodeName)}: CompositeNodeHandle<${ref.entity}Wrapper>;`,
      );
    }
    compositeLines.push(`  readonly ${propKey(compositeName)}: {\n${nodeLines.join("\n")}\n  };`);
  }
  return (
    `${NODE_HANDLE_DTS}\n` +
    `${wrapperBlocks.join("\n")}\n` +
    `export declare const nodes: {\n${compositeLines.join("\n")}\n};\n`
  );
}

/** model.d.ts — types only, precise per-entity Data / Wrapper / Entity interfaces. */
export function emitModelDts(manifest: ModelManifest, nodeViews?: NodeViews): string {
  const entityBlocks = manifest.entities.map(entityDts).join("\n");
  const entitiesType = manifest.entities
    .map((e) => `  readonly ${e.name}: ${e.name}Entity;`)
    .join("\n");
  return (
    `${GENERATED_HEADER}` +
    `import type { DataFactory, DatasetCore, Term } from "@rdfjs/types";\n` +
    `import type { EntityWrapper, ModelManifest } from "@jeswr/model-runtime";\n` +
    `import type { Store } from "n3";\n\n` +
    `${entityBlocks}\n` +
    `${nodeViewsDts(nodeViews)}\n` +
    `export interface GeneratedModel {\n` +
    `  readonly manifest: ModelManifest;\n` +
    `  readonly prefixes: Record<string, string>;\n` +
    `  readonly entities: {\n${entitiesType}\n  };\n` +
    `}\n\n` +
    `export declare const entities: GeneratedModel["entities"];\n` +
    `declare const model: GeneratedModel;\n` +
    `export default model;\n`
  );
}

/** shapes.ttl — the skolemized, byte-reproducible stable waist. */
export function emitShapesTtl(shapes: NormalizedShapes, prefixes: Record<string, string>): string {
  return serializeCanonicalTurtle(shapes.quads, prefixes);
}
